package jp.ac.kyushu.ait.posl.utils.exception;
/**
 * This exception happens when anonymous errors happens during test exercises
 */
public class TestUnknownFailureException extends Exception{
}
